export const searchSuggestionsData = [
    { id: '1', name: 'Thịt heo xào cải thìa', searched: true },
    { id: '2', name: 'Thịt heo nướng sả cháy tỏi ớt', searched: true },
    { id: '3', name: 'Thịt heo nướng sả cháy tỏi ớt', searched: false },
    { id: '4', name: 'Thịt heo nướng sả cháy tỏi ớt', searched: false },
    { id: '5', name: 'Thịt heo nướng sả cháy tỏi ớt', searched: false },
    { id: '6', name: 'Thịt heo nướng sả cháy tỏi ớt', searched: false },
    { id: '7', name: 'Thịt heo nướng sả cháy tỏi ớt', searched: false },
    { id: '8', name: 'Thịt heo nướng sả cháy tỏi ớt', searched: false },
    { id: '9', name: 'Thịt heo nướng sả cháy tỏi ớt', searched: false },
    { id: '10', name: 'Cá kho tộ', searched: true },
    { id: '11', name: 'Gà nướng mật ong', searched: false },
    { id: '12', name: 'Bún bò Huế', searched: false },
    { id: '13', name: 'Phở bò', searched: true },
    { id: '14', name: 'Bánh mì thịt nướng', searched: false },
    { id: '15', name: 'Chả cá Lã Vọng', searched: false },
    { id: '16', name: 'Bún chả Hà Nội', searched: true },
    { id: '17', name: 'Cơm tấm Sài Gòn', searched: false },
    { id: '18', name: 'Bánh xèo miền Tây', searched: false },
    { id: '19', name: 'Lẩu thái', searched: false },
    { id: '20', name: 'Nem nướng Nha Trang', searched: true },
];